### ISSUE TITLE
有没有方法可以修改好友历史排行榜的通关次数啊

### ISSUE THREAD

**Issue by louavo** [lyzcren/sheep_win#1]

**Comment by rslywhj** [comment]
直接调用接口速通，完成数就会加上

**Comment by louavo** [comment]
> 直接调用接口速通，完成数就会加上

我想让他减改那个参数

**Comment by rslywhj** [comment]
> > 直接调用接口速通，完成数就会加上
> 
> 我想让他减改那个参数

原理是直接记录通关成功。。so不能减

**Comment by louavo** [comment]
> > > 直接调用接口速通，完成数就会加上
> > 
> > 
> > 我想让他减改那个参数
> 
> 原理是直接记录通关成功。。so不能减

不能减，只能加。。。

**Comment by Zerek-Cheng** [comment]
有没有办法通过好友的排行榜拿到好友的uid呢。。

**Comment by louavo** [comment]
> 有没有办法通过排行榜拿到好友的uid呢。。

不能吧
